// Code generated by "stringer -type OriginTypeEnum -linecomment"; DO NOT EDIT.

package utils

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OriginTypeBuildIn-1]
	_ = x[OriginTypeAttendance-2]
	_ = x[OriginTypeErp-3]
}

const _OriginTypeEnum_name = "内部考勤erp"

var _OriginTypeEnum_index = [...]uint8{0, 6, 12, 15}

func (i OriginTypeEnum) String() string {
	i -= 1
	if i >= OriginTypeEnum(len(_OriginTypeEnum_index)-1) {
		return "OriginTypeEnum(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _OriginTypeEnum_name[_OriginTypeEnum_index[i]:_OriginTypeEnum_index[i+1]]
}
