// Code generated by "stringer -type StaffStatusEnum -linecomment"; DO NOT EDIT.

package utils

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StaffStatusEmployed-1]
	_ = x[StaffStatusUnEmployed-2]
}

const _StaffStatusEnum_name = "在职离职"

var _StaffStatusEnum_index = [...]uint8{0, 6, 12}

func (i StaffStatusEnum) String() string {
	i -= 1
	if i >= StaffStatusEnum(len(_StaffStatusEnum_index)-1) {
		return "StaffStatusEnum(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _StaffStatusEnum_name[_StaffStatusEnum_index[i]:_StaffStatusEnum_index[i+1]]
}
