// Code generated by "stringer -type StaffTypeEnum -linecomment"; DO NOT EDIT.

package utils

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StaffTypeRegular-1]
	_ = x[StaffTypeTemporary-1]
}

const _StaffTypeEnum_name = "正式工"

var _StaffTypeEnum_index = [...]uint8{0, 9}

func (i StaffTypeEnum) String() string {
	i -= 1
	if i >= StaffTypeEnum(len(_StaffTypeEnum_index)-1) {
		return "StaffTypeEnum(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _StaffTypeEnum_name[_StaffTypeEnum_index[i]:_StaffTypeEnum_index[i+1]]
}
